nguage: node_js
node_js:
  - "4.2.4"

before_script:
  - echo "Using firefox version `firefox --version`"
  - npm install 
  - npm install -g grunt
  - npm install -g bower
  - npm install -g coveralls
  - npm install -g codacy-coverage
  - bower install

script:
  - npm test

after_success:
  - npm run coveralls
  - npm run codacy

notifications:
  - email: false

sudo: false